- hosts: app
  become: yes
  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: nginx, tags: nginx }
    - { role: php, tags: php }
    - { role: mariadb, tags: mariadb }
    - { role: redis, tags: redis }
    - { role: jenkins, tags: jenkins }
    - { role: sonarqube, tags: sonarqube }
